Post.destroy_all

post1 = Post.create!(name: "Diana B. Gobar", photo_url: "https://pbs.twimg.com/profile_images/793280191015641088/axS7aP7j.jpg", description: "I am a developer and would like some help with my cover letter", resume: "put google docs link here")
post2 = Post.create!(name: "John Doe", photo_url: "http://alcarazweb.com/images/Jhon-Doe.jpg", description: "Changed jobs and need to revamp my resume. Please give me some advice on mine!", resume: "put google docs link here")
post3 = Post.create!(name: "Nancy Drough", photo_url: "http://www.teklinks.com/wp-content/uploads/2015/03/Laurie-headshot.jpg", description: "Selfmade business woman. Changing careers, Please help me update my resume", resume: "put google doc link here")
post4 = Post.create!(name: "Jeanne De Beaux", photo_url: "http://www.thehappinessagenda.com/wp-content/uploads/2013/06/Stacy-Boegem-Headshot-2013-oval.png", description: "Relocated from Paris, and looking to update my resume!", resume: "put google docs link here")
post5 = Post.create!(name: "Mary-Lou Tyler", photo_url:"http://crossvilleinc.com/wordpress/wp-content/uploads/2016/05/Denise-McGaha-headshot-300x300.jpg", description: "Looking to get some review on my recently changed resume, thanks!", resume: "put google docs link here")
post6 = Post.create!(name: "Jim Lefferson", photo_url:"http://www.teklinks.com/wp-content/uploads/2015/03/Jim-headshot.jpg", description: "Changing careers and would like a more creative resume. Advice needed.", resume: "put google docs link here")
post7 = Post.create!(name: "Albert Newsome", photo_url:"http://api.theweek.com/sites/default/files/author-images/Auslin_Headshot.png", description: "Finished Business school and looking for some changes in my resume.", resume: "put google docs link here")
post8 = Post.create!(name: "Samantha Houston", photo_url:"http://www.pcrg.org/wp-content/uploads/2016/07/Alix-Headshot-652x652.jpg", description: "I'm looking for jobs for the first time. Could use a review of my resume, headshot, etc.", resume: "put google docs link here")
